# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here

print(np.__version__)

1.26.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1

a = np.random.random((2,3,5))
a

array([[[0.79390592, 0.6005369 , 0.41351179, 0.26807279, 0.00648923],
        [0.62103273, 0.05017556, 0.43923812, 0.29568571, 0.8963177 ],
        [0.34153338, 0.26372365, 0.35431121, 0.51892864, 0.5599884 ]],

       [[0.20601822, 0.21559882, 0.44592112, 0.94628938, 0.25354823],
        [0.24283152, 0.59364162, 0.17785607, 0.36797378, 0.42567496],
        [0.98928418, 0.13614119, 0.20700234, 0.17599159, 0.69631196]]])

In [7]:
# Method 2

from numpy import random

a = random.randint(100, size=(2,3,5))

a

array([[[54, 91, 42, 46, 61],
        [26, 11, 96, 20, 48],
        [87, 13, 61, 68,  0]],

       [[30,  5, 63, 50, 50],
        [94, 92, 17, 67, 51],
        [34, 82, 78, 85, 59]]])

In [4]:
# Method 3

a = np.random.rand(2,3,5)

a

array([[[0.03791932, 0.61793964, 0.02418004, 0.4619839 , 0.88830367],
        [0.57244558, 0.94266324, 0.45796518, 0.57802775, 0.29767778],
        [0.32019672, 0.62708292, 0.85208495, 0.99713632, 0.67715608]],

       [[0.5188013 , 0.73320301, 0.81028273, 0.44370421, 0.32685685],
        [0.08168561, 0.29192786, 0.67969384, 0.71054868, 0.44578078],
        [0.67509655, 0.38361213, 0.81313851, 0.46929528, 0.7054381 ]]])

#### 4. Print *a*.


In [5]:
# your code here

a

array([[[0.03791932, 0.61793964, 0.02418004, 0.4619839 , 0.88830367],
        [0.57244558, 0.94266324, 0.45796518, 0.57802775, 0.29767778],
        [0.32019672, 0.62708292, 0.85208495, 0.99713632, 0.67715608]],

       [[0.5188013 , 0.73320301, 0.81028273, 0.44370421, 0.32685685],
        [0.08168561, 0.29192786, 0.67969384, 0.71054868, 0.44578078],
        [0.67509655, 0.38361213, 0.81313851, 0.46929528, 0.7054381 ]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [25]:
# your code here

b = np.random.rand(5,2,3)
b.fill(1)
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [27]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [28]:
# your code here

a.shape == b.shape

#They do not have the same size.

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [32]:
# your answer here

result = np.add(a,b)

#It says I cannot sum them because they have different shapes.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [40]:
# your code here

c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [62]:
# your code/answer here

d = np.add(a,c)
d

#It works because now both matrices have the same shape.

array([[[1.03791932, 1.61793964, 1.02418004, 1.4619839 , 1.88830367],
        [1.57244558, 1.94266324, 1.45796518, 1.57802775, 1.29767778],
        [1.32019672, 1.62708292, 1.85208495, 1.99713632, 1.67715608]],

       [[1.5188013 , 1.73320301, 1.81028273, 1.44370421, 1.32685685],
        [1.08168561, 1.29192786, 1.67969384, 1.71054868, 1.44578078],
        [1.67509655, 1.38361213, 1.81313851, 1.46929528, 1.7054381 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [63]:
# your code/answer here

print(a)

print(d)

#The difference constist in an increment of 1 in d(values). The relation is that both of them have the same shape.

[[[0.03791932 0.61793964 0.02418004 0.4619839  0.88830367]
  [0.57244558 0.94266324 0.45796518 0.57802775 0.29767778]
  [0.32019672 0.62708292 0.85208495 0.99713632 0.67715608]]

 [[0.5188013  0.73320301 0.81028273 0.44370421 0.32685685]
  [0.08168561 0.29192786 0.67969384 0.71054868 0.44578078]
  [0.67509655 0.38361213 0.81313851 0.46929528 0.7054381 ]]]
[[[1.03791932 1.61793964 1.02418004 1.4619839  1.88830367]
  [1.57244558 1.94266324 1.45796518 1.57802775 1.29767778]
  [1.32019672 1.62708292 1.85208495 1.99713632 1.67715608]]

 [[1.5188013  1.73320301 1.81028273 1.44370421 1.32685685]
  [1.08168561 1.29192786 1.67969384 1.71054868 1.44578078]
  [1.67509655 1.38361213 1.81313851 1.46929528 1.7054381 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [64]:
# your code here

e =  np.multiply(a,c)
e

array([[[0.03791932, 0.61793964, 0.02418004, 0.4619839 , 0.88830367],
        [0.57244558, 0.94266324, 0.45796518, 0.57802775, 0.29767778],
        [0.32019672, 0.62708292, 0.85208495, 0.99713632, 0.67715608]],

       [[0.5188013 , 0.73320301, 0.81028273, 0.44370421, 0.32685685],
        [0.08168561, 0.29192786, 0.67969384, 0.71054868, 0.44578078],
        [0.67509655, 0.38361213, 0.81313851, 0.46929528, 0.7054381 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [65]:
# your code/answer here

e == a

#Yes, they are equal because for every element in both matrices, that condition remains True. 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [66]:
np.array_equal(e,a)

#It is true because they have the same shape and elements.

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [67]:
# your code here

d_max = d.max()
print(d_max)
d_min = d.min()
print(d_min)
d_mean = d.mean()
print(d_mean)

1.99713632122805
1.0241800438049347
1.548060951699137


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [68]:
# your code here

f = np.empty([2,3,5])
f

array([[[0.03791932, 0.61793964, 0.02418004, 0.4619839 , 0.88830367],
        [0.57244558, 0.94266324, 0.45796518, 0.57802775, 0.29767778],
        [0.32019672, 0.62708292, 0.85208495, 0.99713632, 0.67715608]],

       [[0.5188013 , 0.73320301, 0.81028273, 0.44370421, 0.32685685],
        [0.08168561, 0.29192786, 0.67969384, 0.71054868, 0.44578078],
        [0.67509655, 0.38361213, 0.81313851, 0.46929528, 0.7054381 ]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [70]:
# your code here

value1 = (d > d_min) & (d < d_mean) #It doesn't let me use "and", so I will use & instead.
value2 = (d < d_max) & (d > d_mean)
value3 = (d == d_mean)
value4 = (d == d_min)
value5 = (d == d_max)

f[value1] = 25
f[value2] = 75
f[value3] = 50
f[value4] = 0
f[value5] = 100

f

array([[[ 25.,  75.,   0.,  25.,  75.],
        [ 75.,  75.,  25.,  75.,  25.],
        [ 25.,  75.,  75., 100.,  75.]],

       [[ 25.,  75.,  75.,  25.,  25.],
        [ 25.,  25.,  75.,  75.,  25.],
        [ 75.,  25.,  75.,  25.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [74]:
# your code here

print(d)

print(f)

[[[1.03791932 1.61793964 1.02418004 1.4619839  1.88830367]
  [1.57244558 1.94266324 1.45796518 1.57802775 1.29767778]
  [1.32019672 1.62708292 1.85208495 1.99713632 1.67715608]]

 [[1.5188013  1.73320301 1.81028273 1.44370421 1.32685685]
  [1.08168561 1.29192786 1.67969384 1.71054868 1.44578078]
  [1.67509655 1.38361213 1.81313851 1.46929528 1.7054381 ]]]
[[[ 25.  75.   0.  25.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  75.  75. 100.  75.]]

 [[ 25.  75.  75.  25.  25.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [107]:
# your code here

f2 = f.astype(str)
type(f2[0][0][0])

f2

array([[['25.0', '75.0', '0.0', '25.0', '75.0'],
        ['75.0', '75.0', '25.0', '75.0', '25.0'],
        ['25.0', '75.0', '75.0', '100.0', '75.0']],

       [['25.0', '75.0', '75.0', '25.0', '25.0'],
        ['25.0', '25.0', '75.0', '75.0', '25.0'],
        ['75.0', '25.0', '75.0', '25.0', '75.0']]], dtype='<U32')

In [112]:
f2 = f.astype(str) #I convert the data type of the matrix to string.

""" 
As I cannot use the strings as valid indeces, I cannot do the following:

f2["25.0"] = "A"
f2["75.0"] = "B"
f2["50.0"] = "C"
f2["0.0"] = "D"
f2["100.0"] = "E"

"""
#I am going to use boolean values, as they are valid indeces.

f2[f2 == "25.0"] = "A"
f2[f2 == "75.0"] = "B"
f2[f2 == "50.0"] = "C"
f2[f2 == "0.0"] = "D"
f2[f2 == "100.0"] = "E"

f2

array([[['A', 'B', 'D', 'A', 'B'],
        ['B', 'B', 'A', 'B', 'A'],
        ['A', 'B', 'B', 'E', 'B']],

       [['A', 'B', 'B', 'A', 'A'],
        ['A', 'A', 'B', 'B', 'A'],
        ['B', 'A', 'B', 'A', 'B']]], dtype='<U32')