# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.25.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [24]:
a = np.random.randint(0,100,(2,3,5))

In [27]:
# Method 2
a = np.random.rand(2,3,5)

In [79]:
# Method 3
a = np.random.choice(np.random.randint(0,100), size=(2,3,5))

#### 4. Print *a*.


In [80]:
# your code here
print(a)

[[[45 27  3  5 34]
  [42 28 33  3 18]
  [17 18 14 48  6]]

 [[ 4  5 21 50  1]
  [31 41 12 46 32]
  [40 39 10 28 36]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [81]:
# your code here
# NOTE: I think the dimension of the matrix "b" is 5x3x2 because of what is written in the following statements. 
b = np.random.randint(1,2,(5,3,2))

#### 6. Print *b*.


In [82]:
# your code here
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [83]:
# your code here

print('Size a: (', len(a), ',', len(a[0]), ',', len(a[0,0]), ')')
print('Size b: (', len(b), ',', len(b[0]), ',', len(b[0,0]), ')')

Size a: ( 2 , 3 , 5 )
Size b: ( 5 , 3 , 2 )


#### 8. Are you able to add *a* and *b*? Why or why not?


In [84]:
# your answer here
c = np.add(a, b)   # It is imposible to add both matrix because the shapes are different.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [85]:
# your code here
c = b.transpose()
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [86]:
# your code/answer here
print('Shape a: ', a.shape)
print('Shape c: ', c.shape)

d = np.add(a, c)   # It is posible to add both matrix because the shapes are equal.

Shape a:  (2, 3, 5)
Shape c:  (2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [91]:
# your code/answer here
print('Matrix a: ', a)
print('\nMatrix d: ', d)

# The different between both matrix is that matrix "d" has the same dimension that matrix "a". But each element of "d" is 
# the sum of each of the elements between "a" and "c".

Matrix a:  [[[45 27  3  5 34]
  [42 28 33  3 18]
  [17 18 14 48  6]]

 [[ 4  5 21 50  1]
  [31 41 12 46 32]
  [40 39 10 28 36]]]

Matrix d:  [[[46 28  4  6 35]
  [43 29 34  4 19]
  [18 19 15 49  7]]

 [[ 5  6 22 51  2]
  [32 42 13 47 33]
  [41 40 11 29 37]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [93]:
# your code here
e = np.multiply(a,c)
print(e)

[[[45 27  3  5 34]
  [42 28 33  3 18]
  [17 18 14 48  6]]

 [[ 4  5 21 50  1]
  [31 41 12 46 32]
  [40 39 10 28 36]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
# Yes, both are the same because each elemento of "a" is multiply by 1 (all of the elements in c are 1).

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [94]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

51 2 25.566666666666666


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [131]:
# your code here
f = np.empty(d.shape)
print(f)

[[[1.99772903 1.27490903 1.21149975 1.64946326 1.0024228 ]
  [1.86493572 1.88211302 1.20769238 1.05395496 1.52286139]
  [1.70762626 1.59759552 1.3637148  1.37429214 1.618805  ]]

 [[1.95376741 1.56081114 1.86659744 1.91058093 1.57803102]
  [1.77889033 1.93487753 1.10618226 1.10706165 1.80972822]
  [1.0309781  1.61083656 1.86285616 1.99407058 1.73816856]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [193]:
# your code here

def populate(empty_array, entry_array):
    # Calculate max, min and mean
    array_max = np.max(entry_array)
    #print('Max: ', array_max)
    array_min = np.min(entry_array)
    #print('Min: ', array_min)
    array_mean = np.mean(entry_array)
    #print('Mean: ', array_mean)
    
    # Obtain populate
    emp_list = empty_array.tolist()   # To operate without Numpy library, I convert the numpy matrix to python list

    for x in list(range( len(entry_array) )):   # The matrix is traversed along the x-axis
    
        for y in list(range( len(entry_array[0]) )):   # The matrix is traversed along the y-axis
        
            for z in list(range( len(entry_array[0,0]) )):   # The matrix is traversed along the z-axis
            
                value = entry_array[x,y,z]   # Each element value is store in the "value" variable
            
                if value >= array_max:   # If value is higher than d_max, store 100
                    emp_list[x][y][z] = float(100)
                    #print('Value is: ', value, ' so is 100')
                
                elif array_max > value > array_mean:   # If value is smaller than d_max and higher than d_mean, store 75
                    emp_list[x][y][z] = float(75)
                    #print('Value is: ', value, ' so is 75')
                
                elif value == array_mean:   # If value is equal to f_mean, store 50
                    emp_list[x][y][z] = float(50)
                    #print('Value is: ', value, ' so is 50')
                
                elif array_mean > value > array_min:   # If value is smaller than d_mean and higher than d_min, store 25 
                    emp_list[x][y][z] = float(25)
                    #print('Value is: ', value, ' so is 25')
                
                elif value == array_min:   # If value is smaller than d_min, store 0
                    emp_list[x][y][z] = float(0)
                    #print('Value is: ', value, ' so is 0')
    return np.array(emp_list)
            
#f2 = populate(f,d)
#print(f2)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [194]:
# your code here
d2_list = [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]

d2 = np.array(d2_list)

f2 = populate(f,d2)
print(f2)

[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [195]:
# your code here

def populate(empty_array, entry_array):
    
    # Calculate max, min and mean
    array_max = np.max(entry_array)
    #print('Max: ', array_max)
    array_min = np.min(entry_array)
    #print('Min: ', array_min)
    array_mean = np.mean(entry_array)
    #print('Mean: ', array_mean)
    
    # Obtain populate
    empty_array.astype(str)
    emp_list = empty_array.tolist()   # To operate without Numpy library, I convert the numpy matrix to python list

    for x in list(range( len(entry_array) )):   # The matrix is traversed along the x-axis
    
        for y in list(range( len(entry_array[0]) )):   # The matrix is traversed along the y-axis
        
            for z in list(range( len(entry_array[0,0]) )):   # The matrix is traversed along the z-axis
            
                value = entry_array[x,y,z]   # Each element value is store in the "value" variable
            
                if value >= array_max:   # If value is higher than d_max, store 100
                    emp_list[x][y][z] = 'E'
                    #print('Value is: ', value, ' so is 100')
                
                elif array_max > value > array_mean:   # If value is smaller than d_max and higher than d_mean, store 75
                    emp_list[x][y][z] = 'D'
                    #print('Value is: ', value, ' so is 75')
                
                elif value == array_mean:   # If value is equal to f_mean, store 50
                    emp_list[x][y][z] = 'C'
                    #print('Value is: ', value, ' so is 50')
                
                elif array_mean > value > array_min:   # If value is smaller than d_mean and higher than d_min, store 25 
                    emp_list[x][y][z] = 'B'
                    #print('Value is: ', value, ' so is 25')
                
                elif value == array_min:   # If value is smaller than d_min, store 0
                    emp_list[x][y][z] = 'A'
                    #print('Value is: ', value, ' so is 0')
    return np.array(emp_list)

In [196]:
f2 = populate(f,d2)
print(f2)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
