# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np


#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.26.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = [np.random.randint(0, 50) for i in range(30)]
a = np.array(a)
a = a.reshape(2, 3, 5)
a

array([[[34,  7, 19, 12, 28],
        [48, 41, 24, 37, 14],
        [21,  2, 34,  5, 33]],

       [[29, 35, 15,  4, 27],
        [29, 44, 21, 10, 29],
        [26, 28, 11, 19,  5]]])

In [4]:
a = np.random.randint(0, 50, 30)
a = a.reshape(2, 3, 5)
a

array([[[ 7, 37,  6, 42, 33],
        [19, 22,  2, 47,  1],
        [46,  6, 42, 22, 44]],

       [[28, 16, 36, 19, 33],
        [ 8, 32, 34,  9, 47],
        [36, 24, 16,  1, 49]]])

In [5]:
a = np.random.randint(0, 50, (2,3,5))
a

array([[[ 2, 18, 10,  6, 29],
        [20,  4, 43,  1,  6],
        [ 0, 43,  9, 38,  3]],

       [[ 8, 43,  7, 11, 31],
        [ 6, 46, 44,  9, 16],
        [28, 36, 31,  3, 27]]])

#### 4. Print *a*.


In [6]:
print(a)

[[[ 2 18 10  6 29]
  [20  4 43  1  6]
  [ 0 43  9 38  3]]

 [[ 8 43  7 11 31]
  [ 6 46 44  9 16]
  [28 36 31  3 27]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones([5, 3, 2])
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
# a + b
a.shape == b.shape # They can only sum if they have the same size

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
c = b.transpose()
print(c.shape)
c

(2, 3, 5)


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
print(a.shape == c.shape)
d = a + c
d

True


array([[[ 3., 19., 11.,  7., 30.],
        [21.,  5., 44.,  2.,  7.],
        [ 1., 44., 10., 39.,  4.]],

       [[ 9., 44.,  8., 12., 32.],
        [ 7., 47., 45., 10., 17.],
        [29., 37., 32.,  4., 28.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(a)
print(d)#  each value of d: d(i, j, k) corresponds to the sum of a(i, j, k) and c(i, j, k)(which is always 1)

[[[ 2 18 10  6 29]
  [20  4 43  1  6]
  [ 0 43  9 38  3]]

 [[ 8 43  7 11 31]
  [ 6 46 44  9 16]
  [28 36 31  3 27]]]
[[[ 3. 19. 11.  7. 30.]
  [21.  5. 44.  2.  7.]
  [ 1. 44. 10. 39.  4.]]

 [[ 9. 44.  8. 12. 32.]
  [ 7. 47. 45. 10. 17.]
  [29. 37. 32.  4. 28.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = a * c
e

array([[[ 2., 18., 10.,  6., 29.],
        [20.,  4., 43.,  1.,  6.],
        [ 0., 43.,  9., 38.,  3.]],

       [[ 8., 43.,  7., 11., 31.],
        [ 6., 46., 44.,  9., 16.],
        [28., 36., 31.,  3., 27.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
a == e # Yes because echa value of e: e(i, j, k) correesponds to multiplication of a(i, j, k) and c(i, j, k)(which is always 1)
# if I mulitiply every value by 1 it stays the same.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

47.0
1.0
20.266666666666666


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
f = np.empty((2, 3, 5))# I don't know why it automatically populates with the values of the last np.array I have declared
f

array([[[ 2., 18., 10.,  6., 29.],
        [20.,  4., 43.,  1.,  6.],
        [ 0., 43.,  9., 38.,  3.]],

       [[ 8., 43.,  7., 11., 31.],
        [ 6., 46., 44.,  9., 16.],
        [28., 36., 31.,  3., 27.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
def quartiles(x):
    if x == d_min:
        return 0
    elif x < d_mean:
        return 25
    elif x == d_mean:
        return 50
    elif x < d_max:
        return 75
    else:
        return 100


In [19]:
f  = np.array([[list(map(quartiles,j)) for j in i] for i in d])
f

array([[[ 25,  25,  25,  25,  75],
        [ 75,  25,  75,  25,  25],
        [  0,  75,  25,  75,  25]],

       [[ 25,  75,  25,  25,  75],
        [ 25, 100,  75,  25,  25],
        [ 75,  75,  75,  25,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
print(d)
print(f)# yes i have my expected result

[[[ 3. 19. 11.  7. 30.]
  [21.  5. 44.  2.  7.]
  [ 1. 44. 10. 39.  4.]]

 [[ 9. 44.  8. 12. 32.]
  [ 7. 47. 45. 10. 17.]
  [29. 37. 32.  4. 28.]]]
[[[ 25  25  25  25  75]
  [ 75  25  75  25  25]
  [  0  75  25  75  25]]

 [[ 25  75  25  25  75]
  [ 25 100  75  25  25]
  [ 75  75  75  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [21]:
def quartilesl(x):
    if x == d_min:
        return 'A'
    elif x < d_mean:
        return 'B'
    elif x == d_mean:
        return 'C'
    elif x < d_max:
        return 'D'
    else:
        return 'E'


In [22]:
g  = np.array([[list(map(quartilesl,j)) for j in i] for i in d])
g

array([[['B', 'B', 'B', 'B', 'D'],
        ['D', 'B', 'D', 'B', 'B'],
        ['A', 'D', 'B', 'D', 'B']],

       [['B', 'D', 'B', 'B', 'D'],
        ['B', 'E', 'D', 'B', 'B'],
        ['D', 'D', 'D', 'B', 'D']]], dtype='<U1')