# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
print(np.__version__)

1.25.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [14]:
a = np.random.random((2,3,5))

In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [5]:
print(a)

[[[0.53724888 0.18178803 0.65706333 0.14018916 0.95650195]
  [0.53585161 0.04085367 0.05221968 0.93225729 0.37928726]
  [0.71332118 0.33571948 0.74982514 0.71725648 0.25339293]]

 [[0.41241603 0.94207451 0.69971528 0.76514219 0.34277541]
  [0.29835553 0.30392993 0.08309554 0.22993218 0.51256211]
  [0.64145631 0.81263836 0.17432788 0.74384825 0.15707062]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
b = np.ones((5,2,3))

In [23]:
print(b.shape)

(5, 2, 3)


#### 6. Print *b*.


In [12]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [16]:
print(f"Is {a.size == b.size} that a and b have the same size")

Is True that a and b have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [17]:
print(np.add(a, b))

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [18]:
a.shape == b.shape

False

In [ ]:
#Solution: You can not add a and b because they do not have the same shape, the ValueError returned specify the problem

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [32]:
c = b.transpose(1,2,0)

In [33]:
print(c.shape)

(2, 3, 5)


In [34]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [ ]:
# your code/answer here

In [94]:
d = np.add(a, c)

In [39]:
c.shape == a.shape

True

In [38]:
print(d)

[[[1.88342108 1.50909527 1.79844285 1.14842725 1.76713532]
  [1.06649041 1.87115124 1.62851704 1.62013912 1.52747951]
  [1.8517827  1.94866286 1.27780483 1.033374   1.59889617]]

 [[1.81415434 1.68251605 1.18546232 1.4048956  1.9999877 ]
  [1.35700966 1.87652576 1.769817   1.1791896  1.14585407]
  [1.99814015 1.39561374 1.56591286 1.97168543 1.37924754]]]


In [ ]:
#Solution: It works now because they a and c have now the same shape so you can apply operations to them

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
# your code/answer here

In [40]:
print(a)

[[[0.88342108 0.50909527 0.79844285 0.14842725 0.76713532]
  [0.06649041 0.87115124 0.62851704 0.62013912 0.52747951]
  [0.8517827  0.94866286 0.27780483 0.033374   0.59889617]]

 [[0.81415434 0.68251605 0.18546232 0.4048956  0.9999877 ]
  [0.35700966 0.87652576 0.769817   0.1791896  0.14585407]
  [0.99814015 0.39561374 0.56591286 0.97168543 0.37924754]]]


In [41]:
print(d)

[[[1.88342108 1.50909527 1.79844285 1.14842725 1.76713532]
  [1.06649041 1.87115124 1.62851704 1.62013912 1.52747951]
  [1.8517827  1.94866286 1.27780483 1.033374   1.59889617]]

 [[1.81415434 1.68251605 1.18546232 1.4048956  1.9999877 ]
  [1.35700966 1.87652576 1.769817   1.1791896  1.14585407]
  [1.99814015 1.39561374 1.56591286 1.97168543 1.37924754]]]


In [ ]:
#In terms of the values, d values are a values increase by one (values of b)

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here

In [42]:
e = np.multiply(a, c)

In [43]:
print(e)

[[[0.88342108 0.50909527 0.79844285 0.14842725 0.76713532]
  [0.06649041 0.87115124 0.62851704 0.62013912 0.52747951]
  [0.8517827  0.94866286 0.27780483 0.033374   0.59889617]]

 [[0.81415434 0.68251605 0.18546232 0.4048956  0.9999877 ]
  [0.35700966 0.87652576 0.769817   0.1791896  0.14585407]
  [0.99814015 0.39561374 0.56591286 0.97168543 0.37924754]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

In [46]:
print(a)

[[[0.88342108 0.50909527 0.79844285 0.14842725 0.76713532]
  [0.06649041 0.87115124 0.62851704 0.62013912 0.52747951]
  [0.8517827  0.94866286 0.27780483 0.033374   0.59889617]]

 [[0.81415434 0.68251605 0.18546232 0.4048956  0.9999877 ]
  [0.35700966 0.87652576 0.769817   0.1791896  0.14585407]
  [0.99814015 0.39561374 0.56591286 0.97168543 0.37924754]]]


In [47]:
e.shape == a.shape

True

In [50]:
e.ndim == a.ndim

True

In [48]:
e.size == a.size

True

In [44]:
 e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [ ]:
# e and a are the same matrix because e = a (2x3x5) * identity matrix (2x3x5) = a

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

In [95]:
d_max = d.max()
print(d_max)

1.9999876986772587


In [96]:
d_min = d.min()
print(d_min)

1.033373996692529


In [97]:
d_mean = np.mean(d)
print(d_mean)

1.575227716828562


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

In [59]:
f = np.empty((2,3,5))

In [60]:
print(f)

[[[0.88342108 0.50909527 0.79844285 0.14842725 0.76713532]
  [0.06649041 0.87115124 0.62851704 0.62013912 0.52747951]
  [0.8517827  0.94866286 0.27780483 0.033374   0.59889617]]

 [[0.81415434 0.68251605 0.18546232 0.4048956  0.9999877 ]
  [0.35700966 0.87652576 0.769817   0.1791896  0.14585407]
  [0.99814015 0.39561374 0.56591286 0.97168543 0.37924754]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

In [111]:
def check(x):
    if d_min < x < d_mean:
        return 25
    elif d_mean < x < d_max:
        return 75
    elif x == d_mean:
        return 50
    elif x == d_min:
        return 0
    elif x == d_max:
        return 100

In [112]:
f = np.array([[ list(map(check,j)) for j in sublist ] for sublist in d])

In [100]:
print(f)

[[[ 75  25  75  25  75]
  [ 25  75  75  75  25]
  [ 75  75  25   0  75]]

 [[ 75  75  25  25 100]
  [ 25  75  75  25  25]
  [ 75  25  25  75  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

In [113]:
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

In [114]:
print(f)

[[[75 75 75 25 75]
  [75 75 25 75 25]
  [75 25 75 75 75]]

 [[25 25 None 25 75]
  [75 75 75 75 75]
  [25 75 None 75 75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here

In [121]:
def check_string(x):
    if d_min < x < d_mean:
        return "B"
    elif d_mean < x < d_max:
        return "D"
    elif x == d_mean:
        return "C"
    elif x == d_min:
        return "A"
    elif x == d_max:
        return "E"

In [122]:
f = np.array([[ list(map(check_string,j)) for j in sublist ] for sublist in d])

In [123]:
print(f)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'D' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' None 'B' 'D']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' None 'D' 'D']]]
