# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
print(np.__version__)

1.25.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
a = np.random.random((2, 3, 5))
a

array([[[0.05899936, 0.09913062, 0.15788645, 0.22975486, 0.32204248],
        [0.2810157 , 0.2237204 , 0.68829334, 0.33544152, 0.65043401],
        [0.09695066, 0.3799419 , 0.04597534, 0.21929348, 0.7677393 ]],

       [[0.16899912, 0.8527258 , 0.11808509, 0.76909927, 0.043724  ],
        [0.25023212, 0.62562286, 0.04990047, 0.32684027, 0.69292535],
        [0.80750911, 0.24222677, 0.59510274, 0.30490269, 0.60400331]]])

In [7]:
a = np.random.rand(2,3,5)
print(a)

[[[0.10686023 0.50268322 0.4350564  0.49151762 0.9521009 ]
  [0.55187407 0.61232239 0.2979599  0.93107362 0.09265867]
  [0.09057964 0.78804179 0.45608445 0.63274852 0.53906631]]

 [[0.53868948 0.62255829 0.18408845 0.92037535 0.1873745 ]
  [0.27236141 0.93636028 0.30724177 0.06525317 0.27944174]
  [0.01837039 0.29364538 0.55022907 0.45386937 0.44666834]]]


In [8]:
a = np.random.randint(30, size = (2,3,5))
a

array([[[ 3, 18,  4,  2, 15],
        [24, 28, 25, 21, 15],
        [ 6, 16,  3, 16,  8]],

       [[17,  8,  3, 15, 21],
        [11, 28,  4, 20,  0],
        [10, 13, 21,  6, 15]]])

#### 4. Print *a*.


In [9]:
print(a)

[[[ 3 18  4  2 15]
  [24 28 25 21 15]
  [ 6 16  3 16  8]]

 [[17  8  3 15 21]
  [11 28  4 20  0]
  [10 13 21  6 15]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [11]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
a.size
b.size

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
#No,because they have different shape

In [14]:
print(np.add(a, b))

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [17]:
c = b.transpose(1,2,0)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [20]:
a.size
c.size

a.size == c.size

True

In [21]:
d = np.add (a,c)

print(a.shape)
print(c.shape)

(2, 3, 5)
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [23]:
print(a)


[[[0.67115411 0.70859404 0.60598366 0.16334714 0.37500876]
  [0.6976195  0.12495364 0.09545954 0.41396679 0.22788391]
  [0.65301325 0.93632346 0.74607955 0.58075709 0.72159253]]

 [[0.57091117 0.45999348 0.79346754 0.59005506 0.5577968 ]
  [0.20823787 0.09337792 0.6761003  0.51506251 0.82107136]
  [0.97909629 0.10567169 0.99459229 0.43331748 0.15918543]]]


In [25]:
print(d)

[[[1.67115411 1.70859404 1.60598366 1.16334714 1.37500876]
  [1.6976195  1.12495364 1.09545954 1.41396679 1.22788391]
  [1.65301325 1.93632346 1.74607955 1.58075709 1.72159253]]

 [[1.57091117 1.45999348 1.79346754 1.59005506 1.5577968 ]
  [1.20823787 1.09337792 1.6761003  1.51506251 1.82107136]
  [1.97909629 1.10567169 1.99459229 1.43331748 1.15918543]]]


In [27]:
print(np.add(a, d))

[[[2.34230822 2.41718807 2.21196732 1.32669428 1.75001752]
  [2.39523901 1.24990728 1.19091909 1.82793359 1.45576782]
  [2.30602649 2.87264692 2.4921591  2.16151417 2.44318506]]

 [[2.14182234 1.91998696 2.58693507 2.18011012 2.1155936 ]
  [1.41647575 1.18675585 2.3522006  2.03012502 2.64214272]
  [2.95819258 1.21134338 2.98918459 1.86663497 1.31837086]]]


In [ ]:
#In d the values have 1 and in a they are only decimals

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [28]:
e = np.multiply(a,c)
print(e)

[[[0.67115411 0.70859404 0.60598366 0.16334714 0.37500876]
  [0.6976195  0.12495364 0.09545954 0.41396679 0.22788391]
  [0.65301325 0.93632346 0.74607955 0.58075709 0.72159253]]

 [[0.57091117 0.45999348 0.79346754 0.59005506 0.5577968 ]
  [0.20823787 0.09337792 0.6761003  0.51506251 0.82107136]
  [0.97909629 0.10567169 0.99459229 0.43331748 0.15918543]]]


In [29]:
print(a)

[[[0.67115411 0.70859404 0.60598366 0.16334714 0.37500876]
  [0.6976195  0.12495364 0.09545954 0.41396679 0.22788391]
  [0.65301325 0.93632346 0.74607955 0.58075709 0.72159253]]

 [[0.57091117 0.45999348 0.79346754 0.59005506 0.5577968 ]
  [0.20823787 0.09337792 0.6761003  0.51506251 0.82107136]
  [0.97909629 0.10567169 0.99459229 0.43331748 0.15918543]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
#Yes, are equal, both have the same size and shape

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [30]:
d_max = d.max()
print (d_max)


1.9945922927951418


In [31]:
d_min = d.min()
print (d_min)

1.0933779229830507


In [32]:
d_mean = d.mean()
print (d_mean)

1.522655805586087


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [33]:
f = np.empty((2,3,5))
f

array([[[0.67115411, 0.70859404, 0.60598366, 0.16334714, 0.37500876],
        [0.6976195 , 0.12495364, 0.09545954, 0.41396679, 0.22788391],
        [0.65301325, 0.93632346, 0.74607955, 0.58075709, 0.72159253]],

       [[0.57091117, 0.45999348, 0.79346754, 0.59005506, 0.5577968 ],
        [0.20823787, 0.09337792, 0.6761003 , 0.51506251, 0.82107136],
        [0.97909629, 0.10567169, 0.99459229, 0.43331748, 0.15918543]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [42]:
d_mean = np.mean(d)
d_min = np.min(d)
d_max = np.max(d)

f = np.zeros_like(d)
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100
f


array([[[ 75.,  75.,  75.,  25.,  25.],
        [ 75.,  25.,  25.,  25.,  25.],
        [ 75.,  75.,  75.,  75.,  75.]],

       [[ 75.,  25.,  75.,  75.,  75.],
        [ 25.,   0.,  75.,  25.,  75.],
        [ 75.,  25., 100.,  25.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [43]:
print(d)

[[[1.67115411 1.70859404 1.60598366 1.16334714 1.37500876]
  [1.6976195  1.12495364 1.09545954 1.41396679 1.22788391]
  [1.65301325 1.93632346 1.74607955 1.58075709 1.72159253]]

 [[1.57091117 1.45999348 1.79346754 1.59005506 1.5577968 ]
  [1.20823787 1.09337792 1.6761003  1.51506251 1.82107136]
  [1.97909629 1.10567169 1.99459229 1.43331748 1.15918543]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [49]:
g = np.empty_like(d, dtype=str)

# Assign string labels to 'f' based on conditions
g[(d > d_min) & (d < d_mean)] = 'B'
g[(d > d_mean) & (d < d_max)] = 'D'
g[d == d_mean] = 'C'
g[d == d_min] = 'A'
g[d == d_max] = 'E'
unique_labels_in_g = np.unique(g)
g_reshaped = g.reshape(2, 3, 5)

print(g_reshaped)

[[['D' 'D' 'D' 'B' 'B']
  ['D' 'B' 'B' 'B' 'B']
  ['D' 'D' 'D' 'D' 'D']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'A' 'D' 'B' 'D']
  ['D' 'B' 'E' 'B' 'B']]]
