# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.25.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [57]:
# Method 1  >> Utilizando el método .random y .randint, indicando el elemento máximo (50) y el tamaño de 2x3x5
a = np.random.randint(50, size=(2,3,5))
print(a)

[[[24 30 20  7 48]
  [43 32 47 46 19]
  [ 3 29 15 40 10]]

 [[12 11  6 41 33]
  [12 35 41 11 16]
  [16 34  5 37  9]]]


In [58]:
# Method 2   >> Utilizando el método .random y .rand que, en lugar de forzar a enteros, te devuelve float. 
a = np.random.rand(2, 3, 5)   
print(a)

[[[0.35635005 0.06659302 0.43805997 0.88841131 0.96445228]
  [0.79070032 0.87981317 0.90531329 0.41034586 0.55678433]
  [0.53644511 0.17276798 0.83819897 0.34595039 0.47249003]]

 [[0.31852313 0.09843757 0.50198007 0.35360374 0.84259849]
  [0.85421154 0.85121072 0.67830229 0.60576122 0.44354347]
  [0.34360622 0.92238385 0.40990567 0.72403246 0.42061712]]]


In [59]:
# Method 3   >>> Utilizando el método .random y .uniform
a = np.random.uniform(size=(2, 3, 5))
print(a)

[[[0.57014602 0.698741   0.34263806 0.03074618 0.834281  ]
  [0.02583447 0.51025187 0.75347332 0.77734876 0.19390622]
  [0.81871682 0.517811   0.63422553 0.75789412 0.41675054]]

 [[0.20052381 0.06483712 0.5076533  0.32185213 0.56838209]
  [0.07331055 0.53365962 0.27510891 0.12160117 0.58981696]
  [0.24071683 0.18970979 0.61568258 0.08615558 0.27807235]]]


#### 4. Print *a*.


In [60]:
# your code here
print(a)

[[[0.57014602 0.698741   0.34263806 0.03074618 0.834281  ]
  [0.02583447 0.51025187 0.75347332 0.77734876 0.19390622]
  [0.81871682 0.517811   0.63422553 0.75789412 0.41675054]]

 [[0.20052381 0.06483712 0.5076533  0.32185213 0.56838209]
  [0.07331055 0.53365962 0.27510891 0.12160117 0.58981696]
  [0.24071683 0.18970979 0.61568258 0.08615558 0.27807235]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [61]:
# your code here
b = np.ones((5,2,3))
#print(b.ndim)      # Número dimensiones=3
#print(b.shape)     # Forma de la matriz


#### 6. Print *b*.


In [62]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [63]:
# your code here
print(a.size)
print(b.size)
print(a.size == b.size)

# Yes, is the same size. You can check it by looking at the size attribute with .size

30
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [64]:
# your answer here
c_concat = np.concatenate((a, b)) # No puedes utilizar .concatenate porque todas las dimensiones deben concidir 
d_add = np.add(a, b)               # Tampoco se pueden sumar por lo mismo, no tienen la misma forma (2,3,5) vs (5,2,3)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [65]:
# your code here

c = b.reshape(2,3,5)
print(c)

#print(c.ndim)      # Número dimensiones=3
#print(c.shape)     # Forma de la matriz

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [66]:
# your code/answer here
d = np.add(a, c)
print(d)


# He utiliza el método .add para sumar las dos variables. Ahora es posible porque ambas tienen la misma forma. 

[[[1.57014602 1.698741   1.34263806 1.03074618 1.834281  ]
  [1.02583447 1.51025187 1.75347332 1.77734876 1.19390622]
  [1.81871682 1.517811   1.63422553 1.75789412 1.41675054]]

 [[1.20052381 1.06483712 1.5076533  1.32185213 1.56838209]
  [1.07331055 1.53365962 1.27510891 1.12160117 1.58981696]
  [1.24071683 1.18970979 1.61568258 1.08615558 1.27807235]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [67]:
# your code/answer here
print(a)
print(d)

# Tienen el mismo número de elementos y la misma forma. Únicamente los valores en d son la suma de la a + 1

[[[0.57014602 0.698741   0.34263806 0.03074618 0.834281  ]
  [0.02583447 0.51025187 0.75347332 0.77734876 0.19390622]
  [0.81871682 0.517811   0.63422553 0.75789412 0.41675054]]

 [[0.20052381 0.06483712 0.5076533  0.32185213 0.56838209]
  [0.07331055 0.53365962 0.27510891 0.12160117 0.58981696]
  [0.24071683 0.18970979 0.61568258 0.08615558 0.27807235]]]
[[[1.57014602 1.698741   1.34263806 1.03074618 1.834281  ]
  [1.02583447 1.51025187 1.75347332 1.77734876 1.19390622]
  [1.81871682 1.517811   1.63422553 1.75789412 1.41675054]]

 [[1.20052381 1.06483712 1.5076533  1.32185213 1.56838209]
  [1.07331055 1.53365962 1.27510891 1.12160117 1.58981696]
  [1.24071683 1.18970979 1.61568258 1.08615558 1.27807235]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [68]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.57014602 0.698741   0.34263806 0.03074618 0.834281  ]
  [0.02583447 0.51025187 0.75347332 0.77734876 0.19390622]
  [0.81871682 0.517811   0.63422553 0.75789412 0.41675054]]

 [[0.20052381 0.06483712 0.5076533  0.32185213 0.56838209]
  [0.07331055 0.53365962 0.27510891 0.12160117 0.58981696]
  [0.24071683 0.18970979 0.61568258 0.08615558 0.27807235]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [69]:
# your code/answer here
print(a)
print(e)
print(a == e)

# Sí, porque al multiplicarlo x 1 devuelve el mismo resultado. 

[[[0.57014602 0.698741   0.34263806 0.03074618 0.834281  ]
  [0.02583447 0.51025187 0.75347332 0.77734876 0.19390622]
  [0.81871682 0.517811   0.63422553 0.75789412 0.41675054]]

 [[0.20052381 0.06483712 0.5076533  0.32185213 0.56838209]
  [0.07331055 0.53365962 0.27510891 0.12160117 0.58981696]
  [0.24071683 0.18970979 0.61568258 0.08615558 0.27807235]]]
[[[0.57014602 0.698741   0.34263806 0.03074618 0.834281  ]
  [0.02583447 0.51025187 0.75347332 0.77734876 0.19390622]
  [0.81871682 0.517811   0.63422553 0.75789412 0.41675054]]

 [[0.20052381 0.06483712 0.5076533  0.32185213 0.56838209]
  [0.07331055 0.53365962 0.27510891 0.12160117 0.58981696]
  [0.24071683 0.18970979 0.61568258 0.08615558 0.27807235]]]
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [70]:
# your code here
print(d)

d_max = np.array(d.max())
print(d_max)

d_min = np.array(d.min())
print(d_min)

d_mean = np.array(d.mean())
print(d_mean)

[[[1.57014602 1.698741   1.34263806 1.03074618 1.834281  ]
  [1.02583447 1.51025187 1.75347332 1.77734876 1.19390622]
  [1.81871682 1.517811   1.63422553 1.75789412 1.41675054]]

 [[1.20052381 1.06483712 1.5076533  1.32185213 1.56838209]
  [1.07331055 1.53365962 1.27510891 1.12160117 1.58981696]
  [1.24071683 1.18970979 1.61568258 1.08615558 1.27807235]]]
1.8342810041955278
1.025834469518743
1.4183282574536136


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [71]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[1.57014602 1.698741   1.34263806 1.03074618 1.834281  ]
  [1.02583447 1.51025187 1.75347332 1.77734876 1.19390622]
  [1.81871682 1.517811   1.63422553 1.75789412 1.41675054]]

 [[1.20052381 1.06483712 1.5076533  1.32185213 1.56838209]
  [1.07331055 1.53365962 1.27510891 1.12160117 1.58981696]
  [1.24071683 1.18970979 1.61568258 1.08615558 1.27807235]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [72]:
mask_mean = d == d_mean
f[mask_mean] = 50
print(f)

[[[1.57014602 1.698741   1.34263806 1.03074618 1.834281  ]
  [1.02583447 1.51025187 1.75347332 1.77734876 1.19390622]
  [1.81871682 1.517811   1.63422553 1.75789412 1.41675054]]

 [[1.20052381 1.06483712 1.5076533  1.32185213 1.56838209]
  [1.07331055 1.53365962 1.27510891 1.12160117 1.58981696]
  [1.24071683 1.18970979 1.61568258 1.08615558 1.27807235]]]


In [73]:
mask_min = d == d_min
f[mask_min] = 0
print(f)

[[[1.57014602 1.698741   1.34263806 1.03074618 1.834281  ]
  [0.         1.51025187 1.75347332 1.77734876 1.19390622]
  [1.81871682 1.517811   1.63422553 1.75789412 1.41675054]]

 [[1.20052381 1.06483712 1.5076533  1.32185213 1.56838209]
  [1.07331055 1.53365962 1.27510891 1.12160117 1.58981696]
  [1.24071683 1.18970979 1.61568258 1.08615558 1.27807235]]]


In [74]:
mask_max = d == d_max
f[mask_max] = 100
print(f)

[[[  1.57014602   1.698741     1.34263806   1.03074618 100.        ]
  [  0.           1.51025187   1.75347332   1.77734876   1.19390622]
  [  1.81871682   1.517811     1.63422553   1.75789412   1.41675054]]

 [[  1.20052381   1.06483712   1.5076533    1.32185213   1.56838209]
  [  1.07331055   1.53365962   1.27510891   1.12160117   1.58981696]
  [  1.24071683   1.18970979   1.61568258   1.08615558   1.27807235]]]


In [75]:
mask1 = (d > d_min) & (d < d_mean)
f[mask1] = 25 
print(f)

[[[  1.57014602   1.698741    25.          25.         100.        ]
  [  0.           1.51025187   1.75347332   1.77734876  25.        ]
  [  1.81871682   1.517811     1.63422553   1.75789412  25.        ]]

 [[ 25.          25.           1.5076533   25.           1.56838209]
  [ 25.           1.53365962  25.          25.           1.58981696]
  [ 25.          25.           1.61568258  25.          25.        ]]]


In [76]:
mask2 = (d > d_mean) & (d < d_max)
f[mask2] = 75
print(f)

[[[ 75.  75.  25.  25. 100.]
  [  0.  75.  75.  75.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  25.  75.  25.  25.]]]


In [77]:
print(f)

[[[ 75.  75.  25.  25. 100.]
  [  0.  75.  75.  75.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  25.  75.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [78]:
# your code here
print(d)
print(f) 

[[[1.57014602 1.698741   1.34263806 1.03074618 1.834281  ]
  [1.02583447 1.51025187 1.75347332 1.77734876 1.19390622]
  [1.81871682 1.517811   1.63422553 1.75789412 1.41675054]]

 [[1.20052381 1.06483712 1.5076533  1.32185213 1.56838209]
  [1.07331055 1.53365962 1.27510891 1.12160117 1.58981696]
  [1.24071683 1.18970979 1.61568258 1.08615558 1.27807235]]]
[[[ 75.  75.  25.  25. 100.]
  [  0.  75.  75.  75.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  25.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here

In [79]:
f2 = f.astype(str)
print(f)

[[[ 75.  75.  25.  25. 100.]
  [  0.  75.  75.  75.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  25.  75.  25.  25.]]]


In [88]:
f2[f2 == '25.0'] = 'A'
f2[f2 == '75.0'] = 'B'
f2[f2 == '50.0'] = 'C'
f2[f2 == '0.0'] = 'D'
f2[f2 == '100.0'] = 'E'
print(f2)

[[['B' 'B' 'A' 'A' 'E']
  ['D' 'B' 'B' 'B' 'A']
  ['B' 'B' 'B' 'B' 'A']]

 [['A' 'A' 'B' 'A' 'B']
  ['A' 'B' 'A' 'A' 'B']
  ['A' 'A' 'B' 'A' 'A']]]
