# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np
import random

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.24.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [26]:
# Method 1
a = np.random.rand(2,3,5)
a

array([[[0.70935154, 0.30704618, 0.1270475 , 0.01512622, 0.38430271],
        [0.11465612, 0.80056696, 0.36818119, 0.97973747, 0.18289487],
        [0.06956242, 0.91955742, 0.70207856, 0.93036692, 0.27139668]],

       [[0.72176483, 0.67975283, 0.08750476, 0.01979464, 0.8743595 ],
        [0.668723  , 0.11392743, 0.44124987, 0.93680366, 0.19548471],
        [0.90834596, 0.19458757, 0.23327967, 0.43783574, 0.04447211]]])

In [8]:
# Method 2
a = np.random.randint(0, 100, size=(2, 3, 5))
a

array([[[27, 89, 72, 38, 93],
        [87, 35, 67, 59, 35],
        [47, 19, 53,  8, 28]],

       [[24,  3, 23, 76, 88],
        [82, 57, 91, 63, 76],
        [51, 72, 43, 81, 35]]])

In [17]:
# Method 3
a = np.random.random((2,3,5))
a

array([[[0.94951431, 0.41513091, 0.15260206, 0.01110836, 0.60660633],
        [0.0706278 , 0.52538932, 0.90516942, 0.68588507, 0.3726678 ],
        [0.78668626, 0.97314807, 0.04332314, 0.09792448, 0.93375921]],

       [[0.53640664, 0.41864178, 0.14941388, 0.58712052, 0.43935103],
        [0.13177696, 0.68410692, 0.17049615, 0.60899069, 0.46416446],
        [0.20501754, 0.38488915, 0.08418078, 0.85507021, 0.40567628]]])

#### 4. Print *a*.


In [27]:
# your code here
a

array([[[0.70935154, 0.30704618, 0.1270475 , 0.01512622, 0.38430271],
        [0.11465612, 0.80056696, 0.36818119, 0.97973747, 0.18289487],
        [0.06956242, 0.91955742, 0.70207856, 0.93036692, 0.27139668]],

       [[0.72176483, 0.67975283, 0.08750476, 0.01979464, 0.8743595 ],
        [0.668723  , 0.11392743, 0.44124987, 0.93680366, 0.19548471],
        [0.90834596, 0.19458757, 0.23327967, 0.43783574, 0.04447211]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [57]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [58]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [59]:
# your code here
if a.size == b.size:
    print ("Same size")
else:
    print ("Different size")

Same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [50]:
# your answer here
print("It is not possible because they are not the same shape")


It is not possible because they are not the same shape


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [60]:
# your code here
c = b.transpose()
c.shape

(3, 2, 5)

In [61]:
print("It does not become a 2x3x5 array")

It does not become a 2x3x5 array


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [63]:
# I am going to create new one to perform the calculations below
c = np.ones((2,3,5))

In [64]:
# your code/answer here
d = np.add(a,c)
d

array([[[1.70935154, 1.30704618, 1.1270475 , 1.01512622, 1.38430271],
        [1.11465612, 1.80056696, 1.36818119, 1.97973747, 1.18289487],
        [1.06956242, 1.91955742, 1.70207856, 1.93036692, 1.27139668]],

       [[1.72176483, 1.67975283, 1.08750476, 1.01979464, 1.8743595 ],
        [1.668723  , 1.11392743, 1.44124987, 1.93680366, 1.19548471],
        [1.90834596, 1.19458757, 1.23327967, 1.43783574, 1.04447211]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [68]:
# your code/answer here
print (a)
print (d)
print ("The difference is that every value in d is 1.0 higher than a")

[[[0.70935154 0.30704618 0.1270475  0.01512622 0.38430271]
  [0.11465612 0.80056696 0.36818119 0.97973747 0.18289487]
  [0.06956242 0.91955742 0.70207856 0.93036692 0.27139668]]

 [[0.72176483 0.67975283 0.08750476 0.01979464 0.8743595 ]
  [0.668723   0.11392743 0.44124987 0.93680366 0.19548471]
  [0.90834596 0.19458757 0.23327967 0.43783574 0.04447211]]]
[[[1.70935154 1.30704618 1.1270475  1.01512622 1.38430271]
  [1.11465612 1.80056696 1.36818119 1.97973747 1.18289487]
  [1.06956242 1.91955742 1.70207856 1.93036692 1.27139668]]

 [[1.72176483 1.67975283 1.08750476 1.01979464 1.8743595 ]
  [1.668723   1.11392743 1.44124987 1.93680366 1.19548471]
  [1.90834596 1.19458757 1.23327967 1.43783574 1.04447211]]]
The difference is that every value in d is 1.0 higher than a


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [70]:
# your code here
e = np.multiply(a,c)
e

array([[[0.70935154, 0.30704618, 0.1270475 , 0.01512622, 0.38430271],
        [0.11465612, 0.80056696, 0.36818119, 0.97973747, 0.18289487],
        [0.06956242, 0.91955742, 0.70207856, 0.93036692, 0.27139668]],

       [[0.72176483, 0.67975283, 0.08750476, 0.01979464, 0.8743595 ],
        [0.668723  , 0.11392743, 0.44124987, 0.93680366, 0.19548471],
        [0.90834596, 0.19458757, 0.23327967, 0.43783574, 0.04447211]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [71]:
# your code/answer here
print("Yes because a number times 1 equals the number")

Yes because a number times 1 equals the number


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [72]:
# your code here
d_max = d.max()
d_max

1.9797374667478325

In [73]:
d_min = d.min()
d_min

1.015126222037511

In [74]:
d_mean = d.mean()
d_mean

1.4479919683700497

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [83]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.70935154, 0.30704618, 0.1270475 , 0.01512622, 0.38430271],
        [0.11465612, 0.80056696, 0.36818119, 0.97973747, 0.18289487],
        [0.06956242, 0.91955742, 0.70207856, 0.93036692, 0.27139668]],

       [[0.72176483, 0.67975283, 0.08750476, 0.01979464, 0.8743595 ],
        [0.668723  , 0.11392743, 0.44124987, 0.93680366, 0.19548471],
        [0.90834596, 0.19458757, 0.23327967, 0.43783574, 0.04447211]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [86]:
d

array([[[1.70935154, 1.30704618, 1.1270475 , 1.01512622, 1.38430271],
        [1.11465612, 1.80056696, 1.36818119, 1.97973747, 1.18289487],
        [1.06956242, 1.91955742, 1.70207856, 1.93036692, 1.27139668]],

       [[1.72176483, 1.67975283, 1.08750476, 1.01979464, 1.8743595 ],
        [1.668723  , 1.11392743, 1.44124987, 1.93680366, 1.19548471],
        [1.90834596, 1.19458757, 1.23327967, 1.43783574, 1.04447211]]])

In [109]:
# your code here
g = []
for i in d.flatten():
    if i > d_min and i < d_mean:
        g.append(25)
    elif i > d_mean and i < d_max:
        g.append(75)
    elif i == d_mean:
        g.append(50)
    elif i == d_min:
        g.append(0)
    elif i == d_max:
        g.append(100)

f = np.array(g)
f = f.reshape(2,3,5)
f

array([[[ 75,  25,  25,   0,  25],
        [ 25,  75,  25, 100,  25],
        [ 25,  75,  75,  75,  25]],

       [[ 75,  75,  25,  25,  75],
        [ 75,  25,  25,  75,  25],
        [ 75,  25,  25,  25,  25]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [110]:
# your code here
print(d)
print(f)

[[[1.70935154 1.30704618 1.1270475  1.01512622 1.38430271]
  [1.11465612 1.80056696 1.36818119 1.97973747 1.18289487]
  [1.06956242 1.91955742 1.70207856 1.93036692 1.27139668]]

 [[1.72176483 1.67975283 1.08750476 1.01979464 1.8743595 ]
  [1.668723   1.11392743 1.44124987 1.93680366 1.19548471]
  [1.90834596 1.19458757 1.23327967 1.43783574 1.04447211]]]
[[[ 75  25  25   0  25]
  [ 25  75  25 100  25]
  [ 25  75  75  75  25]]

 [[ 75  75  25  25  75]
  [ 75  25  25  75  25]
  [ 75  25  25  25  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [120]:
# your code here
k = []
for element in d:
    for j in element:
        for i in j:
            if i > d_min and i < d_mean:
                k.append("B")
            elif i > d_mean and i < d_max:
                k.append("D")
            elif i == d_mean:
                k.append("C")
            elif i == d_min:
                k.append("A")
            elif i == d_max:
                k.append("E")
m = np.array(k)
print(m.reshape(2,3,5))
print("No sé hacerlo sin np")

[[['D' 'B' 'B' 'A' 'B']
  ['B' 'D' 'B' 'E' 'B']
  ['B' 'D' 'D' 'D' 'B']]

 [['D' 'D' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'B']
  ['D' 'B' 'B' 'B' 'B']]]
No sé hacerlo sin np
