# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here (https://www.delftstack.com/es/howto/numpy/numpy-version-python/)

print(np.__version__)

1.25.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1 => np.linspace()

a = np.linspace(1, 83, 30)
a = np.array(np.round(a,2))
a = a.reshape((2,3,5))
a_method_1 = a
print(a_method_1.ndim)

3


In [4]:
# Method 2 => np.random.rand()
a = np.random.rand(2,3,5)
a = np.array(np.round(a,2))
a_method_2 = a
print(a_method_2.ndim)

3


In [5]:
# Method 3 => np.random.rand()
a = np.random.randint(1, 83, (2,3,5))
a = np.array(np.round(a,2))
a_method_3 = a
print(a_method_3.ndim)

3


#### 4. Print *a*.


In [6]:
# your code here (a_method_1)
print(a_method_1)
print(a_method_1.shape)

[[[ 1.    3.83  6.66  9.48 12.31]
  [15.14 17.97 20.79 23.62 26.45]
  [29.28 32.1  34.93 37.76 40.59]]

 [[43.41 46.24 49.07 51.9  54.72]
  [57.55 60.38 63.21 66.03 68.86]
  [71.69 74.52 77.34 80.17 83.  ]]]
(2, 3, 5)


In [7]:
# your code here (a_method_2)
print(a_method_2)
print(a_method_2.shape)

[[[0.95 0.46 0.22 0.86 0.43]
  [0.1  0.95 0.38 0.2  0.01]
  [0.4  0.92 0.09 0.47 0.27]]

 [[0.75 0.66 0.23 0.26 0.43]
  [0.37 0.8  0.09 0.9  0.9 ]
  [0.08 0.49 0.24 0.78 0.56]]]
(2, 3, 5)


In [8]:
# your code here (a_method_3)
print(a_method_3)
print(a_method_3.shape)

[[[79 25 58 65 19]
  [12 77 34  6 18]
  [34 67 32 61 16]]

 [[65 59 17 19 31]
  [41 43 59 32 16]
  [31 58 23 42 15]]]
(2, 3, 5)


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
# your code here

b = np.ones((5,2,3))
print(b.ndim)

3


#### 6. Print *b*.


In [10]:
# your code here
print(b)
print(b.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
# your code here => .size
a = a_method_1
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
# your answer here
a + b

'''ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5)
They need to be the same shape to add each other up'''

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
# your code here
c = b.transpose()
print(c.shape) # This statement was done on purpose: Is not a 2x3x5, but 3x2x5

(3, 2, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
# your code/answer here
'd = a + c' # Returns an error, but:

c = c.reshape(2,3,5)

# Now we can sum a + c and assign it to d:
d = a + c
d
print(d.shape)

(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code
print(f'a = {a}')
print('----------------')
print(f'd = {d}')

# answer here
'''What I notice is each value from d is summed by 1.'''

a = [[[ 1.    3.83  6.66  9.48 12.31]
  [15.14 17.97 20.79 23.62 26.45]
  [29.28 32.1  34.93 37.76 40.59]]

 [[43.41 46.24 49.07 51.9  54.72]
  [57.55 60.38 63.21 66.03 68.86]
  [71.69 74.52 77.34 80.17 83.  ]]]
----------------
d = [[[ 2.    4.83  7.66 10.48 13.31]
  [16.14 18.97 21.79 24.62 27.45]
  [30.28 33.1  35.93 38.76 41.59]]

 [[44.41 47.24 50.07 52.9  55.72]
  [58.55 61.38 64.21 67.03 69.86]
  [72.69 75.52 78.34 81.17 84.  ]]]


'What I notice is each value from d is summed by 1.'

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here
e = a * c
print(e)

[[[ 1.    3.83  6.66  9.48 12.31]
  [15.14 17.97 20.79 23.62 26.45]
  [29.28 32.1  34.93 37.76 40.59]]

 [[43.41 46.24 49.07 51.9  54.72]
  [57.55 60.38 63.21 66.03 68.86]
  [71.69 74.52 77.34 80.17 83.  ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code
print(e.ndim == a.ndim)
print(e.shape == a.shape)
print(e.size == a.size)

True
True
True


In [18]:
# /answer here
print(e.shape)
print(e.ndim)
print(e.size)
'''a & e have the same shape (2,3,5), both are 3-Dimensional and contains 30 int elements'''

(2, 3, 5)
3
30


'a & e have the same shape (2,3,5), both are 3-Dimensional and contains 30 int elements'

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
# your code here
print('d =', d)
print('---------------')

# Max:
d_max = d.max()
print(f'd_max = {d_max}')

# Min:
d_min = d.min()
print(f'd_min = {d_min}')

# Mean:
d_mean = np.mean(d)
print(f'd_mean = {d_mean}')

d = [[[ 2.    4.83  7.66 10.48 13.31]
  [16.14 18.97 21.79 24.62 27.45]
  [30.28 33.1  35.93 38.76 41.59]]

 [[44.41 47.24 50.07 52.9  55.72]
  [58.55 61.38 64.21 67.03 69.86]
  [72.69 75.52 78.34 81.17 84.  ]]]
---------------
d_max = 84.0
d_min = 2.0
d_mean = 43.0


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [20]:
# your code here (https://numpy.org/doc/stable/reference/generated/numpy.empty.html#)

print(d.shape)
f = np.empty((2,3,5))
print(f)
'''It returns the same d array'''

(2, 3, 5)
[[[ 2.    4.83  7.66 10.48 13.31]
  [16.14 18.97 21.79 24.62 27.45]
  [30.28 33.1  35.93 38.76 41.59]]

 [[44.41 47.24 50.07 52.9  55.72]
  [58.55 61.38 64.21 67.03 69.86]
  [72.69 75.52 78.34 81.17 84.  ]]]


'It returns the same d array'

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [21]:
'''For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.'''
# your code here
f[(d > d_min) & (d < d_mean)] = 25
print(f'f = {f}')

f = [[[ 2.   25.   25.   25.   25.  ]
  [25.   25.   25.   25.   25.  ]
  [25.   25.   25.   25.   25.  ]]

 [[44.41 47.24 50.07 52.9  55.72]
  [58.55 61.38 64.21 67.03 69.86]
  [72.69 75.52 78.34 81.17 84.  ]]]


In [22]:
'''If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.'''
# your code here
f[(d > d_mean) & (d < d_max)] = 75
print(f'f = {f}')

f = [[[ 2. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]

 [[75. 75. 75. 75. 75.]
  [75. 75. 75. 75. 75.]
  [75. 75. 75. 75. 84.]]]


In [23]:
'''If a value equals to d_mean, assign 50 to the corresponding value in f.'''
# your code here
f[d == d_mean] = 50
print(f'f = {f}')

f = [[[ 2. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]

 [[75. 75. 75. 75. 75.]
  [75. 75. 75. 75. 75.]
  [75. 75. 75. 75. 84.]]]


In [24]:
'''# Assign 0 to the corresponding value(s) in f for d_min in d.'''
# your code here
f[d == d_min] = 0
print(f'f = {f}')

f = [[[ 0. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]

 [[75. 75. 75. 75. 75.]
  [75. 75. 75. 75. 75.]
  [75. 75. 75. 75. 84.]]]


In [25]:
'''# Assign 100 to the corresponding value(s) in f for d_max in d.'''
# your code here
f[d == d_max] = 100
print(f'f = {f}')

f = [[[  0.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75. 100.]]]


In [26]:
'''# In the end, f should have only the following values: 0, 25, 50, 75, and 100.'''
# your code here
print(f'f = {f}')

f = [[[  0.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75. 100.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [27]:
# your code here
print(f'd = {d}')
print('--------------------------------------')
print(f'f = {f}')
print('--------------------------------------')
print('Based on the question, I got the expected answer')

d = [[[ 2.    4.83  7.66 10.48 13.31]
  [16.14 18.97 21.79 24.62 27.45]
  [30.28 33.1  35.93 38.76 41.59]]

 [[44.41 47.24 50.07 52.9  55.72]
  [58.55 61.38 64.21 67.03 69.86]
  [72.69 75.52 78.34 81.17 84.  ]]]
--------------------------------------
f = [[[  0.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75. 100.]]]
--------------------------------------
Based on the question, I got the expected answer


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [29]:
f

array([[[  0.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  25.]],

       [[ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75., 100.]]])

In [35]:
# List comprehensions
string_array = [[[('A' if i == 0 else 'B' if i == 25 else 'C' if i == 50 else 'D' if i == 75 else 'E') for i in row] 
                 for row in subarray] for subarray in f]
string_array

[[['A', 'B', 'B', 'B', 'B'],
  ['B', 'B', 'B', 'B', 'B'],
  ['B', 'B', 'B', 'B', 'B']],
 [['D', 'D', 'D', 'D', 'D'],
  ['D', 'D', 'D', 'D', 'D'],
  ['D', 'D', 'D', 'D', 'E']]]