# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.__version__)

1.25.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.randint(1,100,(2,3,5))
# array aleatorios entre 1 y 99. de 6 filas y 5 elementos por columna

In [4]:
a

array([[[60, 39, 53, 86, 55],
        [31,  1, 44, 78, 74],
        [ 4, 34, 21, 29,  7]],

       [[25, 55, 71, 34,  5],
        [67, 79, 21, 34, 70],
        [ 3, 16, 53, 25, 43]]])

In [5]:
# Method 2
a = np.random.rand(2,3,5)
#rellenela con muestras aleatorias de una distribución uniforme sobre [0, 1)

In [6]:
a

array([[[0.51795732, 0.51004993, 0.87919793, 0.25379221, 0.4774647 ],
        [0.49002443, 0.08466991, 0.67721063, 0.46333661, 0.05489534],
        [0.08671659, 0.62504672, 0.23303641, 0.15544298, 0.94064764]],

       [[0.50529525, 0.26005835, 0.33551993, 0.32945755, 0.97288121],
        [0.45111699, 0.08958034, 0.04670151, 0.47258017, 0.64549579],
        [0.61652443, 0.11118797, 0.39806141, 0.11862999, 0.79528814]]])

In [7]:
# Method 3
a = np.random.randn(2,3,5)
#Devuelve una muestra (o muestras) de la distribución “estándar normal”. A diferencia del rand que es uniforme

In [8]:
a

array([[[-1.17117659, -1.21114396, -0.21216065, -0.57962521,
          0.40400528],
        [ 0.97848513,  1.09333507,  0.76781744,  0.91676405,
         -0.22360985],
        [ 0.62637517,  0.92426898, -1.05598622,  0.70859167,
          0.13149388]],

       [[-0.80196831, -1.12879031,  0.19628027,  0.04263611,
          1.41937958],
        [ 0.59308846, -0.31341795, -2.51974315,  0.28227946,
          1.14878493],
        [ 2.30001248, -1.08007554, -0.00924123, -0.54098761,
         -1.28945106]]])

#### 4. Print *a*.


In [9]:
# your code here
print(a)

[[[-1.17117659 -1.21114396 -0.21216065 -0.57962521  0.40400528]
  [ 0.97848513  1.09333507  0.76781744  0.91676405 -0.22360985]
  [ 0.62637517  0.92426898 -1.05598622  0.70859167  0.13149388]]

 [[-0.80196831 -1.12879031  0.19628027  0.04263611  1.41937958]
  [ 0.59308846 -0.31341795 -2.51974315  0.28227946  1.14878493]
  [ 2.30001248 -1.08007554 -0.00924123 -0.54098761 -1.28945106]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
# your code here
b = np.ones((5,2,3))


In [11]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [12]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
# your code here
print(a.size)
print(a.shape)

30
(2, 3, 5)


In [14]:
print(b.size)
print(b.shape)

30
(5, 2, 3)


In [15]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [17]:
# your answer here
#suma = a + b
#suma
#no se puede sumar porque las dimensiones del array no tienen el mismo tamaño

In [18]:
a.shape

(2, 3, 5)

In [19]:
b.shape

(5, 2, 3)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [20]:
# your code here
print(b)
b2 = np.transpose(b)
c = b2.reshape((2,3,5))
c

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [21]:
# your code/answer here
print(a)
print(a.shape)
print(b.shape)
print(c.shape)
d = a + c
d
#Ahora ya podemos sumar porque le hemos cambiado a b su estructura (2, 3, 5)

[[[-1.17117659 -1.21114396 -0.21216065 -0.57962521  0.40400528]
  [ 0.97848513  1.09333507  0.76781744  0.91676405 -0.22360985]
  [ 0.62637517  0.92426898 -1.05598622  0.70859167  0.13149388]]

 [[-0.80196831 -1.12879031  0.19628027  0.04263611  1.41937958]
  [ 0.59308846 -0.31341795 -2.51974315  0.28227946  1.14878493]
  [ 2.30001248 -1.08007554 -0.00924123 -0.54098761 -1.28945106]]]
(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


array([[[-0.17117659, -0.21114396,  0.78783935,  0.42037479,
          1.40400528],
        [ 1.97848513,  2.09333507,  1.76781744,  1.91676405,
          0.77639015],
        [ 1.62637517,  1.92426898, -0.05598622,  1.70859167,
          1.13149388]],

       [[ 0.19803169, -0.12879031,  1.19628027,  1.04263611,
          2.41937958],
        [ 1.59308846,  0.68658205, -1.51974315,  1.28227946,
          2.14878493],
        [ 3.30001248, -0.08007554,  0.99075877,  0.45901239,
         -0.28945106]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [22]:
# your code/answer here
print(a)
print(d)
# d contiene la suma de a + c por eso sus valores son distintos

[[[-1.17117659 -1.21114396 -0.21216065 -0.57962521  0.40400528]
  [ 0.97848513  1.09333507  0.76781744  0.91676405 -0.22360985]
  [ 0.62637517  0.92426898 -1.05598622  0.70859167  0.13149388]]

 [[-0.80196831 -1.12879031  0.19628027  0.04263611  1.41937958]
  [ 0.59308846 -0.31341795 -2.51974315  0.28227946  1.14878493]
  [ 2.30001248 -1.08007554 -0.00924123 -0.54098761 -1.28945106]]]
[[[-0.17117659 -0.21114396  0.78783935  0.42037479  1.40400528]
  [ 1.97848513  2.09333507  1.76781744  1.91676405  0.77639015]
  [ 1.62637517  1.92426898 -0.05598622  1.70859167  1.13149388]]

 [[ 0.19803169 -0.12879031  1.19628027  1.04263611  2.41937958]
  [ 1.59308846  0.68658205 -1.51974315  1.28227946  2.14878493]
  [ 3.30001248 -0.08007554  0.99075877  0.45901239 -0.28945106]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [23]:
# your code here
e = a * c
e

array([[[-1.17117659, -1.21114396, -0.21216065, -0.57962521,
          0.40400528],
        [ 0.97848513,  1.09333507,  0.76781744,  0.91676405,
         -0.22360985],
        [ 0.62637517,  0.92426898, -1.05598622,  0.70859167,
          0.13149388]],

       [[-0.80196831, -1.12879031,  0.19628027,  0.04263611,
          1.41937958],
        [ 0.59308846, -0.31341795, -2.51974315,  0.28227946,
          1.14878493],
        [ 2.30001248, -1.08007554, -0.00924123, -0.54098761,
         -1.28945106]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [24]:
# your code/answer here
e == a
# "e" es igual a "a" porque en la operacion anterior "a" lo hemos multiplicado por 1, por lo tanto no cambia su valor

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [25]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [26]:
print(e)

[[[-1.17117659 -1.21114396 -0.21216065 -0.57962521  0.40400528]
  [ 0.97848513  1.09333507  0.76781744  0.91676405 -0.22360985]
  [ 0.62637517  0.92426898 -1.05598622  0.70859167  0.13149388]]

 [[-0.80196831 -1.12879031  0.19628027  0.04263611  1.41937958]
  [ 0.59308846 -0.31341795 -2.51974315  0.28227946  1.14878493]
  [ 2.30001248 -1.08007554 -0.00924123 -0.54098761 -1.28945106]]]


In [27]:
print(a)

[[[-1.17117659 -1.21114396 -0.21216065 -0.57962521  0.40400528]
  [ 0.97848513  1.09333507  0.76781744  0.91676405 -0.22360985]
  [ 0.62637517  0.92426898 -1.05598622  0.70859167  0.13149388]]

 [[-0.80196831 -1.12879031  0.19628027  0.04263611  1.41937958]
  [ 0.59308846 -0.31341795 -2.51974315  0.28227946  1.14878493]
  [ 2.30001248 -1.08007554 -0.00924123 -0.54098761 -1.28945106]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [28]:
# your code here
d_max =  d.max()
d_max


3.300012482787833

In [29]:
d_min = d.min()
d_min

-1.5197431492765863

In [30]:
d_mean = d.mean()
d_mean

1.0132073437869265

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [31]:
# your code here
f = np.empty([2, 3, 5])
f

array([[[1.17117659, 1.21114396, 0.21216065, 0.57962521, 0.40400528],
        [0.97848513, 1.09333507, 0.76781744, 0.91676405, 0.22360985],
        [0.62637517, 0.92426898, 1.05598622, 0.70859167, 0.13149388]],

       [[0.80196831, 1.12879031, 0.19628027, 0.04263611, 1.41937958],
        [0.59308846, 0.31341795, 2.51974315, 0.28227946, 1.14878493],
        [2.30001248, 1.08007554, 0.00924123, 0.54098761, 1.28945106]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [42]:
mask0 = d == d_min
mask25 = (d > d_min) & (d < d_mean)
mask75 = (d > d_mean) & (d < d_max)
mask50 = d == d_mean
mask100 = d == d_max

f[mask0]= 0
f[mask25]= 25
f[mask75]= 75
f[mask50]= 50
f[mask100]= 100
f 

array([[[ 25.,  25.,  25.,  25.,  75.],
        [ 75.,  75.,  75.,  75.,  25.],
        [ 75.,  75.,  25.,  75.,  75.]],

       [[ 25.,  25.,  75.,  75.,  75.],
        [ 75.,  25.,   0.,  75.,  75.],
        [100.,  25.,  25.,  25.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [43]:
# your code here
print(d)
print(f)

[[[-0.17117659 -0.21114396  0.78783935  0.42037479  1.40400528]
  [ 1.97848513  2.09333507  1.76781744  1.91676405  0.77639015]
  [ 1.62637517  1.92426898 -0.05598622  1.70859167  1.13149388]]

 [[ 0.19803169 -0.12879031  1.19628027  1.04263611  2.41937958]
  [ 1.59308846  0.68658205 -1.51974315  1.28227946  2.14878493]
  [ 3.30001248 -0.08007554  0.99075877  0.45901239 -0.28945106]]]
[[[ 25.  25.  25.  25.  75.]
  [ 75.  75.  75.  75.  25.]
  [ 75.  75.  25.  75.  75.]]

 [[ 25.  25.  75.  75.  75.]
  [ 75.  25.   0.  75.  75.]
  [100.  25.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [50]:
# your code here

g = f.astype(str)
g


array([[['25.0', '25.0', '25.0', '25.0', '75.0'],
        ['75.0', '75.0', '75.0', '75.0', '25.0'],
        ['75.0', '75.0', '25.0', '75.0', '75.0']],

       [['25.0', '25.0', '75.0', '75.0', '75.0'],
        ['75.0', '25.0', '0.0', '75.0', '75.0'],
        ['100.0', '25.0', '25.0', '25.0', '25.0']]], dtype='<U32')

In [54]:
g[g == '0.0'] = 'A'
g[g == '25.0']= 'B'
g[g == '75.0']= 'C'
g[g == '50.0']= 'D'
g[g == '100.0']= 'E'
g 

array([[['B', 'B', 'B', 'B', 'C'],
        ['C', 'C', 'C', 'C', 'B'],
        ['C', 'C', 'B', 'C', 'C']],

       [['B', 'B', 'C', 'C', 'C'],
        ['C', 'B', 'A', 'C', 'C'],
        ['E', 'B', 'B', 'B', 'B']]], dtype='<U32')